apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers:
  - name: app-container
    image: nginx
    resources:
      requests:
      # soft limit
        memory: "64Mi"
        cpu: "250m"
      # hard limit
      limits:
        memory: "128Mi"
        cpu: "500m"
