apiVersion: v1
kind: Pod
metadata:
  name: almalinux
  labels:
    project: roboshop
    env: dev
    component: frontend
spec:
  containers:
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]