apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: frontend
  annotations:
    kubernetes.io/change-cause: "moving to 1.29.7 latest"
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
  template:
    metadata:
      name: nginx
      labels:
        project: roboshop
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    # labels are used as selectors
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port